services:

  3-tools-workspace:
    build:
      context: .
      platforms:
        #- "linux/amd64"
        - "linux/arm64"
      dockerfile: Dockerfile
      args:
        - GO_VERSION=1.24.4
        - USER_NAME=${USER}
    #network_mode: "host"   
    volumes:
      - ../..:/workspaces:cached      
    command: sleep infinity

